# Generated by Django 4.0.2 on 2022-03-10 19:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hccontrolapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastos',
            name='fecha_gasto',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 3, 10, 14, 48, 40, 529671)),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='producto/'),
        ),
        migrations.AlterField(
            model_name='venta_diaria',
            name='fecha_venta',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 3, 10, 14, 48, 40, 530670)),
        ),
        migrations.CreateModel(
            name='Merma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_producto_merma', models.IntegerField()),
                ('fecha', models.DateTimeField(verbose_name=datetime.datetime(2022, 3, 10, 14, 48, 40, 530670))),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hccontrolapp.producto')),
            ],
        ),
    ]
